### ISSUE TITLE
How were you able to do this?  And why isn't Microsoft working on a native ARM version?

### ISSUE THREAD

**Issue by justinhca** [jimm98y/MSSQLEXPRESS-M1-Install#44]
Hi there.  If you could spare a few moments, I was hoping you could provide a little color on how you were able to get the SQL install to work on ARM?  I have some technical background, but really was seeking a few bullets on the general approach on how you made it work.

Sincerely,
Justin H.

**Comment by jimm98y** [comment]
That's a great question! 

I needed SQL server for a pet project I was working on so I've tried to install it only to find out it had failed. I was thinking that there is no reason for SQL to not work on ARM64 in emulation, I've had quite a few x64 apps that were working nicely. I took a look at what was installed and I've tried to run the installation again to see if I can repair it. To my surprise it got me one step further, looking at what was installed I thought I have most of it if not all, suspecting the second failure got me nearly to the end of the installation. I started tinkering around and comparing what was missing - looking at the logs, it was clear we are missing the databases, so I've tried to repair them. I was successful and the SQL had started - few more fixes and I've got a fully working SQL server, at least from my point of view (all the features I needed were there). Then I automated the process and I had the first version of the scripts.

Such approach had its flaws, the major one being that the SQL installation was left unfinished and some features were missing entirely as a result. A year later when I got some free time I've decided to use a different approach. So I started investigating the real cause of the installation failures. Using Process Monitor it was easy to identify the features that were failing and then I just had to come up with a few workarounds, creating the keys the SQL installation was looking for when deciding whether or not to install them. That's basically it, applying this new targeted approach allowed the installation to complete successfully.

The features that were failing the installation were a file system driver used by the Filestream feature (I've never used it, but since it's a system driver, it makes sense it's failing - x64 drivers can't work in emulation on ARM64, Microsoft would have to re-compile them for ARM64) and Azure Attestation service (I don't know what it does and I don't need it).
